### ISSUE TITLE
www.jqueryin.com link in read me is dead?

### ISSUE THREAD

**Issue by iby** [cballou/MongoSession#14]

**Comment by mjomble** [comment]
I found an older version of the page in the web archive:
http://web.archive.org/web/20130209013140/http://www.jqueryin.com/projects/mongo-session

The content seems to be the same as here:
http://blackbe.lt/projects/mongo-session/

But the "MongoDB Performance & Durability" link in there is also dead :)

However, I found that article here:
http://www.futurealoof.com/posts/mongodb-performance-durability.html

But ultimately, the information seems outdated as it talks about problems in Mongo 1.4.4 whereas the latest version at the moment is 2.6 and as far as I know, a lot of these problems have been solved since then. But possibly not all of them.
